import { z } from "zod";
import {
  ActionRequest,
  ActionResult,
  ActionResultsRequest,
  ActionResultsResponse,
  ApiError,
  AssistantContext,
  AssistantTurn,
  ChatRequest,
  DeviceCapabilities,
  TOOL_ARGUMENT_SCHEMAS,
  TOOL_MANIFEST,
  TOOL_NAMES,
} from "../src/index";

/**
 * Builds the generated/ files. Kept pure so the test suite can assert that the
 * committed files are up to date.
 */
export function buildGeneratedFiles(): Record<string, string> {
  const wire = {
    AssistantContext,
    ChatRequest,
    DeviceCapabilities,
    AssistantTurn,
    ActionRequest,
    ActionResult,
    ActionResultsRequest,
    ActionResultsResponse,
    ApiError,
  };

  const wireSchemas = Object.fromEntries(
    Object.entries(wire).map(([name, schema]) => [name, z.toJSONSchema(schema, { io: "input" })]),
  );

  // Tool definitions: manifest metadata + argument JSON Schema. The backend registry
  // loads this file and builds the LLM's function declarations from `parameters`.
  const tools = TOOL_NAMES.map((name) => ({
    name,
    ...TOOL_MANIFEST[name],
    parameters: z.toJSONSchema(TOOL_ARGUMENT_SCHEMAS[name], { io: "input" }),
  }));

  const header = { $comment: "GENERATED by packages/contracts/scripts/export-schemas.ts — do not edit." };

  return {
    "wire.schema.json": json({ ...header, schemas: wireSchemas }),
    "tools.manifest.json": json({ ...header, tools }),
  };
}

function json(value: unknown): string {
  return JSON.stringify(value, null, 2) + "\n";
}
